DELETE FROM category;
INSERT INTO category ("label", "minimumPrice", "maximumPrice", "unit", "placeholder") VALUES
            ('Sans catégorie',20,30,'l''heure','Détaillez la prestation : référence produits, nombre, missions, ...'),
            ('Ampoules',20,30,'les 2 ampoules','Détaillez la prestation : type d''ampoule, nombre, type de luminaires, hauteur...'),
            ('Appliques',20,30,'2 appliques','Détaillez la prestation : référence et marque du produit, nombre de produits, hauteur, ...'),
            ('Autre confort',20,30,'l''heure','Détaillez la prestation : référence et marque du produit, emplacement de l''installation, ...'),
            ('Autre cuisine',20,30,'l''heure','Détaillez la prestation : référence produits, nombre, missions, ...'),
            ('Autre décoration',20,30,'l''heure','Détaillez la prestation : référence et marque du produit, nombre de produits, surface des murs...'),
            ('Autre éclairage',20,30,'l''heure','Détaillez la prestation : référence et marque du produit, nombre de produits, hauteur, ...'),
            ('Autre jardin',20,30,'l''heure','Détaillez la prestation : surface à entretenir, type d''entretien, état du terrain, particularité du terrain,...'),
            ('Autre menuiserie',20,30,'l''heure','Détaillez la prestation : référence produits, nombre, missions, ...'),
            ('Autre meubles',20,30,'l''heure','Détaillez la prestation : référence et marque du meuble, nombre de produits, ...'),
            ('Autre peinture',20,30,'l''heure','Détaillez la prestation : surface à peindre, état du sol,price_details type de pièce, type de peinture, particularité de la pièce, ...'),
            ('Autre plomberie/Électricité',20,30,'l''heure','Détaillez la prestation : référence et marque du produit, nombre de produits, installation existante, ...'),
            ('Autre pose de sol',20,30,'l''heure','Détaillez la prestation : surface à poser, préparation à faire, type de pièce, référence produit, particularité de la pièce, ...'),
            ('Autre quincaillerie',20,30,'l''heure','Détaillez la prestation : référence et marque du produit, nombre de produits,...'),
            ('Autre salle de bain',20,30,'l''heure','Détaillez la prestation : référence produits, nombre, missions, ...'),
            ('Débroussaillage',20,30,'les 10m²','Détaillez la prestation : surface à débroussailler, type de plantations, particularité du terrain,...'),
            ('Découpes',30,60,'les découpes','Détaillez la prestation : type de découpes, nombre, produits, particularités...'),
            ('Déménagement',20,30,'l''heure','Détaillez la prestation : nombre de personnes, durée, type de produits, quantité,...'),
            ('Dressing',60,100,'le dressing','Détaillez la prestation : référence et marque du produit, nombre de produits, ...'),
            ('Enduit',8,12,'le m²','Détaillez la prestation : surface à enduire, état des murs, type de pièce, type d''enduit, particularité de la pièce, ...'),
            ('Étagères - Meubles',15,25,'l''étagère','Détaillez la prestation : référence et marque du produit, nombre de produits, surface des murs...'),
            ('Évier',40,100,'l''évier','Détaillez la prestation : type d''évier, installation existante,...'),
            ('Détecteur de fumée',25,50,'le détecteur','Détaillez la prestation : référence et marque du produit, emplacement de l''installation, ...'),
            ('Entretien de jardin',20,30,'l''heure','Détaillez la prestation : surface à entretenir, type d''entretien, état du terrain, particularité du terrain,...'),
            ('Joints de cuisine',30,80,'la prestation','Détaillez la prestation : longueur, emplacement, état actuel,...'),
            ('Joints de salle de bain',30,80,'la prestation','Détaillez la prestation : longueur, emplacement, état actuel,...'),
            ('Luminaire intérieur',25,35,'le luminaire','Détaillez la prestation : référence et marque du produit, nombre de produits, hauteur, ...'),
            ('Luminaires extérieurs',25,35,'le luminaire','Détaillez la prestation : référence et marque du produit, nombre de produits, hauteur, ...'),
            ('Meuble de cuisine',20,30,'le meuble','Détaillez la prestation : référence et marque du meuble, nombre de produits, ...'),
            ('Meuble de salle de bain',30,80,'le meuble','Détaillez la prestation : référence produits, nombre, missions, ...'),
            ('Meubles divers',20,30,'le meuble','Détaillez la prestation : référence et marque du meuble, nombre de produits, ...'),
            ('Miroirs',20,30,'le miroir','Détaillez la prestation : référence et marque du produit, nombre de produits, surface des murs...'),
            ('Moustiquaires',25,35,'la moustiquaire','Détaillez la prestation : référence et marque du produit, nombre de produits, surface des murs...'),
            ('Papier peint',100,200,'pour une pièce de 10m2','Détaillez la prestation : surface à tapisser, état des murs, type de pièce, particularité de la pièce,...'),
            ('Pare douche',30,80,'le pare douche','Détaillez la prestation : type de produit, dimensions, portes, installation existante,...'),
            ('Peinture au sol',5,8,'le m²','Détaillez la prestation : surface à peindre, état du sol, type de pièce, type de peinture, particularité de la pièce, ...'),
            ('Peinture intérieure',5,8,'le m²','Détaillez la prestation : surface à peindre, état des murs, type de pièce, type de peinture, particularité de la pièce, ...'),
            ('Peinture d''escaliers',5,8,'le m²','Détaillez la prestation : surface à peindre, état du sol, type de pièce, type de peinture, particularité de la pièce, ...'),
            ('Plan de travail',50,100,'le plan de travail','Détaillez la prestation : type de plan de travail, dimension, installation existante,...'),
            ('Plinthes',30,40,'10 mètres linéaires','Détaillez la prestation : surface à poser, préparation à faire, type de pièce, référence produit, particularité de la pièce, ...'),
            ('Pose de carrelage',20,30,'le m²','Détaillez la prestation : surface à poser, préparation à faire, type de pièce, référence produit, particularité de la pièce, ...'),
            ('Pose de crédence',50,100,'les 3m','Détaillez la prestation : type de crédence, longueur, état des murs,...'),
            ('Pose de moquette',10,20,'le m²','Détaillez la prestation : surface à poser, préparation à faire, type de pièce, référence produit, particularité de la pièce, ...'),
            ('Pose de sol PVC / Lino',9,12,'le m²','Détaillez la prestation : surface à poser, préparation à faire, type de pièce, référence produit, particularité de la pièce, ...'),
            ('Pose de stratifié',15,25,'le m²','Détaillez la prestation : surface à poser, préparation à faire, type de pièce, référence produit, particularité de la pièce, ...'),
            ('Prises et interrupteurs',20,30,'2 prises','Détaillez la prestation : référence et marque du produit, nombre de produits, installation existante, ...'),
            ('Rabotage',20,60,'la prestation','Détaillez la prestation : type de rabotages, nombre, produits, particularités...'),
            ('Radiateur électrique',50,100,'le radiateur','Détaillez la prestation : référence et marque du produit, emplacement de l''installation, ...'),
            ('Robinet',40,100,'le robinet','Détaillez la prestation : type de robinet, installation existante,...'),
            ('Scarification',20,30,'les 10m²','Détaillez la prestation : surface à scarifier, état du terrain, particularité du terrain,...'),
            ('Sèche serviette',50,100,'le sèche serviette','Détaillez la prestation : référence et marque du produit, emplacement de l''installation, ...'),
            ('Siphon',30,60,'le siphon','Détaillez la prestation : type de siphon, installation existante,...'),
            ('Spots',20,30,'2 spots','Détaillez la prestation : référence et marque du produit, nombre de produits, hauteur, ...'),
            ('Store banne',150,300,'le store banne','Détaillez la prestation : référence et marque du produit, nombre de produits, hauteur, ...'),
            ('Stores',25,35,'le store','Détaillez la prestation : référence et marque du produit, nombre de produits, surface des murs...'),
            ('Tableaux',15,25,'le tableau','Détaillez la prestation : référence et marque du produit, nombre de produits, surface des murs...'),
            ('Taille de haies',30,40,'les 10m linéaires','Détaillez la prestation : type de feuillage, dimensions (hauteur, largeur, profondeur), accessibilité...'),
            ('Thermostat',30,50,'le thermostat','Détaillez la prestation : référence et marque du produit, emplacement de l''installation, ...'),
            ('Tonte de pelouse',20,30,'pour 10m²','Détaillez la prestation : surface à tondre, hauteur de l''herbe, particularité du terrain,...'),
            ('Tringles à rideaux',20,30,'le rideau','Détaillez la prestation : référence et marque du produit, nombre de produits, surface des murs...'),
            ('WC',150,200,'le WC','Détaillez la prestation : type de WC, installation existante,...');
